#+title: Log
#+created: 2026-06-10T12:32:33+0900

My progress log notebook for training Tesseract for Taigi.

* Install deps

#+begin_src shell
uv venv .venv
uv pip install -r requirements.txt
#+end_src

* Langdata

As the readme mentions. While this will be run automatically we might as well run it first to see what files are around.

#+begin_src shell
make tesseract-langdata
#+end_src

* Choosing model name

I will use =ftg= as the model name. This is currently a bit premature but we can always just rename it to =nan= if that is necessary.

* data/MODEL-ground-truth

#+begin_src shell
mkdir -p data/ftg-ground-truth
#+end_src

The issue is that this seems to need images to be split into lines. I guess I'm not doing this.

* Trying out =TESSDATA=

Unzip ocrd-testset.zip then put it into data/foo-ground-truth as instructed by readme

Can I just specify =START_MODEL= like this?

#+begin_src shell
make training MODEL_NAME=foo START_MODEL=eng
#+end_src

: Failed to read /home/kisaragi-hiu/git/tesstrain/usr/share/tessdata/eng.traineddata

Nope. Can I just use the tessdata that's installed on my system then?

#+begin_src shell
make training MODEL_NAME=foo START_MODEL=eng TESSDATA="/usr/share/tessdata"
#+end_src

+Seemingly yes.+ Nope.

: Error, data/eng/foo.lstm is an integer (fast) model, cannot continue training

#+begin_src shell
mkdir -p data/tessdata
make training MODEL_NAME=foo START_MODEL=eng TESSDATA="data/tessdata"
#+end_src

This doesn't work either. Guess we have to semi-manually download it.

#+begin_src shell
make TESSDATA="data/tessdata" data/tessdata/eng.traineddata
make training MODEL_NAME=foo START_MODEL=eng TESSDATA="data/tessdata"
#+end_src

Yes, this works.

* Preparing data
** DONE Put training text in data/<lang>/<lang>.training_text

Not in README but we can see this in src/tesstrain/arguments.py.

This is one file, not a folder. It is passed to text2image, which is an executable that is also a part of tesseract.

There are two easy sources we can pull this from: Kautian examples plus words etc. collected in Kemdict; or the existing digitization of parts of Taiwan Church News from [[https://github.com/Taiwanese-Corpus/Khin-hoan_2010_pojbh][Taiwanese-Corpus/Khin-hoan_2010_pojbh]]. I'll use the latter.

*** Grab the JSON and make types from it for convenience
#+begin_src shell
wget -O pojbh.json "https://github.com/Taiwanese-Corpus/Khin-hoan_2010_pojbh/raw/master/pojbh.json"
#+end_src

#+begin_src shell
echo '
// deno-lint-ignore-file no-import-prefix no-unversioned-import
import fs from "node:fs";
import { JsonToTS } from "npm:@kemdict/json-to-ts";

const data = JSON.parse(
  fs.readFileSync("pojbh.json", {
    encoding: "utf-8",
  }),
);
fs.writeFileSync(
  "pojbh.json.d.ts",
  JsonToTS(data, { export: true }).join("\n"),
);
' > types.ts
deno run -A types.ts
rm types.ts
#+end_src

(I wish there's a better way)

*** Extract strings from pojbh.json

See =extract.ts=

#+begin_src shell :results none
mkdir -p data/langdata/ftg
node extract.ts > data/langdata/ftg/ftg.training_text.poj
#+end_src

Also throw all valid syllables into the file (relies on =kisaragi-rime-taigi=)

#+begin_src shell :results none
cat ~/git/kisaragi-rime-taigi/taigi-poj.syllables.dict.yaml | sed '/[:\.#-]/d;s/\t.*//' >> data/langdata/ftg/ftg.training_text
#+end_src

Make sure we have both POJ and TL, then merge them back.

#+begin_src shell
bunx @kemdict/kesi --to kip --input data/langdata/ftg/ftg.training_text.poj --output data/langdata/ftg/ftg.training_text.kip
cat data/langdata/ftg/ftg.training_text.poj data/langdata/ftg/ftg.training_text.kip > data/langdata/ftg/ftg.training_text
#+end_src

We don't normalize the original POJ because kesi's normalization kills whitespaces which I kind of want. This should hopefully be fine?

** Generating ground truth

We cannot run training yet as we do not have ground truth.

#+begin_src shell
uv run python src/tesstrain --linedata_only --lang ftg --langdata_dir data/langdata --tessdata_dir data/tessdata --fontlist 'Liberation Serif' 'Noto Serif'
#+end_src

This complains the language code isn't valid. We have to add it to language_specific.py.

** Fine-tune with the training text

#+begin_src sh
make TESSDATA="data/tessdata" data/tessdata/eng.traineddata
make training MODEL_NAME=ftg START_MODEL=eng TESSDATA="data/tessdata"
#+end_src

This creates checkpoint files.

** Create .traineddata from checkpoints

#+begin_src sh
make traineddata MODEL_NAME=ftg
#+end_src

This outputs to data/<model>/ by default.

* Evaluation
#+begin_src shell
make plot MODEL_NAME=ftg
#+end_src

#+begin_src shell
make evaluation MODEL_NAME=ftg
#+end_src

* 2026-06-10T19:12:31+09:00

I see an error about not finding some stuff from Latin during generate?

#+begin_src sh
mkdir -p data/tessdata/script
wget -O data/tessdata/script/Latin.traineddata 'https://github.com/tesseract-ocr/tessdata_best/raw/main/script/Latin.traineddata'
#+end_src
* try using pytesstrain's =create_ground_truth= to split source text (per line) & create .gt.txt + .tif pairs
/2026-07-08T03:12:13+0900: This became 0.1.4. I gave up on it./
  The code is done (hopefully without mistake). Then it's a retrain (git clean + clean =/tmp= for disk space + run the file)
** 2026-06-18T14:25:00+09:00 current result
: At iteration 9875/10000/14218, mean rms=2.305%, delta=32.492%, BCER train=94.463%, BWER train=99.981%, skip ratio=43.200%, New best BCER = 94.463 wrote checkpoint.
: Finished! Selected model with minimal training error rate (BCER) = 94.463
But the resulting model is not usable. Using it on a screenshot just produces basically the same thing as the English model
** 2026-06-18T03:05:47+0900 maybe we should split the text ourselves then run src/tesstrain.

    Currently, we use pytesstrain's =create_ground_truth= to generate the .gt.txt and tif files, then we run =generate_line_box.py= to generate box files from the tif, then we run ~tesseract ... lstm.train~ for each file to get the lstmf file. (This is how the tesstrain Makefile does it.)
    A bunch of errors in the form of
    : Failed to read boxes from data/ftg-ground-truth/ftg.training_text.all.090672.Liberation_Serif.exp0.tif
    : Error during processing.
    show up in this method.

    +If we use src/tesstrain instead, it uses text2image which generates box files together with the image files.+ Wait. pytesstrain also calls text2image. I think I'm overwriting the box files that are already there after =create_ground_truth=. +Fuck. I think we need to regenerate the files (again).+

    ...I'm not sure. In the =make_one_box= function we already return if the file exists. So the box file generation only happens if it wasn't there before.

    Either way. We should try this next. Using =src/tesstrain= has some benefits: we can specify font names that need commas in them (some variants are like this in Pango, like =Roboto Condensed, Condensed= instead of just =Roboto Condensed=); we can specify font list in the language_specific.py file. (If we add real samples (as =png/gt.txt= pairs they will be processed by the Makefile.)

    The core splitting logic in =create_ground_truth= is just this:

    #+begin_src python
    for line_number, line in enumerate(RE_LINE_ENDING.split(source.read_text(encoding='utf8')), 1):
        tidy_line = line.rstrip()
        if not tidy_line:  # Get rid of empty lines
            continue
    #+end_src
* 2026-07-08T03:30:40+0900 annotation of lines
I want a quick tool to annotate lines without having to open a file in Krita → crop → write → undo → crop → write → undo, etc.. That is extremely slow.

I've found the ideal-ish tool to do this, the [[https://gitlab.com/vgg/via-suite/via][VGG image annotator]]. ([[https://www.robots.ox.ac.uk/~vgg/software/via/via.html][Image annotator]]) The output still needs to be converted though, ideally directly to box files similar to those from =text2image=.

char x y x y 0
if char is tab, it represents a newline (make the box 1x1)

generate_line_box.py does this:
chat 0 0 line-width line-height 0

Do box files /need/ to contain the characters? We are simply specifying textlines here, right?
input is configs/lstm.train; probably the parameter =tessedit_train_line_recognizer=
“Break input into lines and remap boxes if present”
[[https://github.com/tesseract-ocr/tesseract/blob/245ad55147fe8fc408a134873fd723857c6741b8/src/api/baseapi.cpp#L793][maps to TrainLineRecognizer function]]
#+begin_src c++
// Generates training data for training a line recognizer, eg LSTM.
// Breaks the page into lines, according to the boxes, and writes them to a
// serialized DocumentData based on output_basename.
// Return true if successful, false if an error occurred.
bool Tesseract::TrainLineRecognizer(const char *input_imagename, const std::string &output_basename, BLOCK_LIST *block_list)
#+end_src
ReadAllBoxes(applybox_page, false, input_imagename, &boxes, &texts, nullptr, nullptr)
  This should succeed as long as our file format is right.
TrainFromBoxes(boxes, texts, block_list, &images)
  This should just figure out bounding boxes of lines (using tab to separate lines) then split the image according to them.
I don't think we need to worry about the text.

(0, 0 is bottom left for Tesseract.)
* 2026-07-10T03:16:57+0900

Actually the recognition of some pages is already quite good apart from quantifiable misidentifications.

- 8th tone on i
- h/b
- c/e
- a/n (should almost always be a)
- 8th tone on à (duplicate tones)
- m̄ frequently becomes mī̄
- ⁿ sometimes becomes "
