#+title: Log
#+created: 2026-06-10T12:32:33+0900

My progress log notebook for training Tesseract for Taigi.

* Install deps

#+begin_src shell
uv venv .venv
uv pip install -r requirements.txt
#+end_src

* Langdata

As the readme mentions. While this will be run automatically we might as well run it first to see what files are around.

#+begin_src shell
make tesseract-langdata
#+end_src

* Choosing model name

I will use =ftg= as the model name. This is currently a bit premature but we can always just rename it to =nan= if that is necessary.

* data/MODEL-ground-truth

#+begin_src shell
mkdir -p data/ftg-ground-truth
#+end_src

The issue is that this seems to need images to be split into lines. I guess I'm not doing this.

* Trying out =TESSDATA=

Unzip ocrd-testset.zip then put it into data/foo-ground-truth as instructed by readme

Can I just specify =START_MODEL= like this?

#+begin_src shell
make training MODEL_NAME=foo START_MODEL=eng
#+end_src

: Failed to read /home/kisaragi-hiu/git/tesstrain/usr/share/tessdata/eng.traineddata

Nope. Can I just use the tessdata that's installed on my system then?

#+begin_src shell
make training MODEL_NAME=foo START_MODEL=eng TESSDATA="/usr/share/tessdata"
#+end_src

+Seemingly yes.+ Nope.

: Error, data/eng/foo.lstm is an integer (fast) model, cannot continue training

#+begin_src shell
mkdir -p data/tessdata
make training MODEL_NAME=foo START_MODEL=eng TESSDATA="data/tessdata"
#+end_src

This doesn't work either. Guess we have to semi-manually download it.

#+begin_src shell
make TESSDATA="data/tessdata" data/tessdata/eng.traineddata
make training MODEL_NAME=foo START_MODEL=eng TESSDATA="data/tessdata"
#+end_src

Yes, this works.

* Preparing data
** DONE Put training text in data/<lang>/<lang>.training_text

Not in README but we can see this in src/tesstrain/arguments.py.

This is one file, not a folder. It is passed to text2image, which is an executable that is also a part of tesseract.

There are two easy sources we can pull this from: Kautian examples plus words etc. collected in Kemdict; or the existing digitization of parts of Taiwan Church News from [[https://github.com/Taiwanese-Corpus/Khin-hoan_2010_pojbh][Taiwanese-Corpus/Khin-hoan_2010_pojbh]]. I'll use the latter.

*** Grab the JSON and make types from it for convenience
#+begin_src shell
wget -O pojbh.json "https://github.com/Taiwanese-Corpus/Khin-hoan_2010_pojbh/raw/master/pojbh.json"
#+end_src

#+begin_src shell
echo '
// deno-lint-ignore-file no-import-prefix no-unversioned-import
import fs from "node:fs";
import { JsonToTS } from "npm:@kemdict/json-to-ts";

const data = JSON.parse(
  fs.readFileSync("pojbh.json", {
    encoding: "utf-8",
  }),
);
fs.writeFileSync(
  "pojbh.json.d.ts",
  JsonToTS(data, { export: true }).join("\n"),
);
' > types.ts
deno run -A types.ts
rm types.ts
#+end_src

(I wish there's a better way)

*** Extract strings from pojbh.json

See =extract.ts=

#+begin_src shell :results none
mkdir -p data/ftg
node extract.ts > data/ftg/ftg.training_text.poj
#+end_src

Also throw all valid syllables into the file (relies on =kisaragi-rime-taigi=)

#+begin_src shell :results none
cat ~/git/kisaragi-rime-taigi/taigi-poj.syllables.dict.yaml | sed '/[:\.#-]/d;s/\t.*//' >> data/ftg/ftg.training_text
#+end_src

Make sure we have both POJ and TL, then merge them back.

#+begin_src shell
bunx @kemdict/kesi --to kip --input data/ftg/ftg.training_text.poj --output data/ftg/ftg.training_text.kip
cat data/ftg/ftg.training_text.poj data/ftg/ftg.training_text.kip > data/ftg/ftg.training_text
#+end_src

We don't normalize the original POJ because kesi's normalization kills whitespaces which I kind of want. This should hopefully be fine?

** Generating ground truth

We cannot run training yet as we do not have ground truth.

#+begin_src shell
uv run python src/tesstrain --linedata_only --lang ftg --langdata_dir data --tessdata_dir data/tessdata --fontlist 'Liberation Serif' 'Noto Serif'
#+end_src

This complains the language code isn't valid. We have to add it to language_specific.py.

** Fine-tune with the training text

#+begin_src sh
make TESSDATA="data/tessdata" data/tessdata/eng.traineddata
make training MODEL_NAME=ftg START_MODEL=eng TESSDATA="data/tessdata"
#+end_src

This creates checkpoint files.

** Create .traineddata from checkpoints

#+begin_src sh
make traineddata MODEL_NAME=ftg
#+end_src

This outputs to data/<model>/ by default.

* Evaluation
#+begin_src shell
make plot MODEL_NAME=ftg
#+end_src

#+begin_src shell
make evaluation MODEL_NAME=ftg
#+end_src

* 2026-06-10T19:12:31+09:00

I see an error about not finding some stuff from Latin during generate?

#+begin_src sh
mkdir -p data/tessdata/script
wget -O data/tessdata/script/Latin.traineddata 'https://github.com/tesseract-ocr/tessdata_best/raw/main/script/Latin.traineddata'
#+end_src
